### ISSUE TITLE
provider code is looking for `apikey` not `appId`

### ISSUE THREAD

**Issue by apfister** [dbouwman/torii-provider-arcgis#1]
when adding in your `torii` config in `config/environment.js`, the readme doc under [Usage](https://github.com/dbouwman/torii-provider-arcgis/blob/59143abb699ae830e08dcf1fbde4fd6589c772b2/README.md#usage) sample code is showing `appId`. this throws an error because it looks like it really wants `apiKey` like you have in your [test app]( https://github.com/dbouwman/torii-provider-arcgis/blob/59143abb699ae830e08dcf1fbde4fd6589c772b2/tests/dummy/config/environment.js#L24)

**Comment by dbouwman** [comment]
Thanks!
